# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ebbed760b8124183f449aab7ca2eb9ba569765594465f043b1893a1715d7d3351d2f53109cf0fc70a5a00cfcd101303cd037facc2e321e3248af2c004a054fa

test:
  secret_key_base: 9a98d9cd14d396f3a30be67d24d3fa5d8957973acbac32e283196ac42850e8ed80953ca65d7001039f9729f910f778012d30d8922454ffd237b8d9c1919caf6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
